---
lgsmhosts:
   hosts:
      production:
         ansible_port: 22
         ansible_host: 192.168.1.100
         ansible_user: ansible
      debian11testing:
         ansible_port: 22
         ansible_host: 192.168.1.99
         ansible_user: ansible
      debian12testing:
         ansible_port: 22
         ansible_host: 192.168.1.98
         ansible_user: ansible
