---
- name: Configure admins cfg
  ansible.builtin.template:
    src: admins.cfg.j2
    dest: "/home/{{ item.user }}/serverfiles/{{ item.directory }}/addons/sourcemod/configs/admins.cfg"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0644"
  loop: "{{ lgsm }}"
  loop_control:
    label: "dest: /home/{{ item.user }}/serverfiles/{{ item.directory }}/addons/sourcemod/configs/admins.cfg"
  tags: admins
