---
lgsmrequirements_lgsm_dependencies:
  - steamcmd
  - bc
  - binutils
  - bsdmainutils
  - bzip2
  - ca-certificates
  - cpio
  - curl
  - distro-info
  - file
  - gzip
  - hostname
  - jq
  - lib32gcc-s1
  - lib32stdc++6
  - libsdl2-2.0-0:i386
  - netcat-openbsd
  - python3
  - tar
  - tmux
  - unzip
  - util-linux
  - uuid-runtime
  - wget
  - xz-utils

lgsmrequirements_contrib: contrib
lgsmrequirements_nonfree: non-free
lgsmrequirements_nonfreefirmware: non-free-firmware
lgsmrequirements_url_deb: http://deb.debian.org/debian/
lgsmrequirements_url_deb_secu: http://security.debian.org/debian-security
