---
configure_iptables_dependencies:
  - iptables
  - iptables-persistent

configure_iptables_ip:
  v4:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
  v6:
    src: rules.v6.j2
    dest: /etc/iptables/rules.v6

configure_iptables_ssh_port: 22
configure_iptables_games_servers_ports: "27015, 27016"
