---
- name: Apt get update
  ansible.builtin.apt:
    update_cache: true
  when: not ansible_check_mode

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Apt get dist upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
    force: true
