---
- name: Copy maps files to remote game server
  ansible.builtin.copy:
    src: "files/{{ item.user }}/maps/"
    dest: "{{ item.path }}/addons"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0644"
  loop: "{{ lgsm }}"
  loop_control:
    label: "src: {{ item.user }}/maps/ dest: {{ item.path }}/addons"
  when: item.maps | bool
  tags: maps
