---
- name: Copy lgsm cfg files to remote game server
  become: true
  ansible.builtin.copy:
    src: "files/{{ item.user }}/lgsm_cfg/"
    dest: "/home/{{ item.user }}/lgsm/config-lgsm/{{ item.game_name }}/"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0644"
  loop: "{{ lgsm }}"
  loop_control:
    label: "dest: /home/{{ item.user }}/lgsm/config-lgsm/{{ item.game_name }}/"
  when: item.lgsm_cfg | bool
  tags: lgsm_cfg
