---
- name: Download lgsm
  become: true
  ansible.builtin.get_url:
    url: "{{ lgsminstallation_lgsm_url_script }}"
    dest: "/home/{{ item.user }}/{{ lgsminstallation_lgsm_script }}"
    mode: "0755"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  loop: "{{ lgsm }}"
  loop_control:
    label: "url: {{ lgsminstallation_lgsm_url_script }} dest: /home/{{ item.user }}/{{ lgsminstallation_lgsm_script }}"
  when: not ansible_check_mode

- name: Create script for a game server
  become: true
  become_user: "{{ item.user }}"
  ansible.builtin.shell: "/home/{{ item.user }}/{{ lgsminstallation_lgsm_script }} {{ item.game_name }}"
  args:
    chdir: "/home/{{ item.user }}"
    creates: "/home/{{ item.user }}/{{ item.game_name }}"
    executable: /usr/bin/bash
  loop: "{{ lgsm }}"
  loop_control:
    label: "creates: /home/{{ item.user }}/{{ item.game_name }}"
  when: not ansible_check_mode

- name: Download and installation of game server
  become: true
  become_user: "{{ item.user }}"
  ansible.builtin.shell: "/home/{{ item.user }}/{{ item.game_name }} auto-install"
  args:
    chdir: "/home/{{ item.user }}"
    creates: "/home/{{ item.user }}/serverfiles"
    executable: /usr/bin/bash
  loop: "{{ lgsm }}"
  loop_control:
    label: "creates: /home/{{ item.user }}/serverfiles"
  when: not ansible_check_mode

- name: Include tasks copy lgsm cfg files
  ansible.builtin.import_tasks: lgsm_cfg.yml

- name: Include tasks copy server cfg files
  ansible.builtin.import_tasks: server_cfg.yml

- name: Include tasks copy server files
  ansible.builtin.import_tasks: serverfiles.yml

- name: Include tasks crontab
  ansible.builtin.import_tasks: crontab.yml
