---
- name: Copy server files to remote game server
  ansible.builtin.copy:
    src: "files/{{ item.user }}/server/"
    dest: "{{ item.path }}/"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0755"
  loop: "{{ lgsm }}"
  loop_control:
    label: "dest: {{ item.path }}/"
  when: item.serverfiles | bool
  tags: serverfiles
