---
useful_packages:
  - linux-cpupower
  - tuned
  - dmidecode
  - lm-sensors
  - htop
  - lsb-release
  - wget
  - curl
  - net-tools
  - traceroute
  - lsof
  - strace
  - dnsutils
  - neofetch
  - gdb

crontab_reboot:
  - name: "Disable hyperthreading"
    job: echo d | /root/toggleHT.sh
